grpc:
  client:
    user-service:
      address: static://localhost:6565
      negotiationType: plaintext
    movie-service:
      address: static://localhost:7575
      negotiationType: TLS
      security:
        trustCertCollection: file:C:\\Users\\USER\\dev\\git\\grpc-java-course\\ssl-tls\\ca.cert.pem